package com.bk.sbs.exception;

public enum ServerErrorCode {
    SUCCESS(0, "Success"),

    HTTP_BAD_REQUEST_400(400, "HTTP_BAD_REQUEST_400"),     // 잘못된 요청
    HTTP_UNAUTHORIZED_401(401, "HTTP_UNAUTHORIZED_401"),    // 인증 안됨
    HTTP_FORBIDDEN_403(403, "HTTP_FORBIDDEN_403"),       // 권한 없음
    HTTP_NOT_FOUND_404(404, "HTTP_NOT_FOUND_404"),       // 서버 찾을 수 없음
    HTTP_SERVER_ERROR_500(500, "HTTP_SERVER_ERROR_500"),    // 서버 에러

    GENERAL_ACCOUNT_REGISTER_FAIL_REASON1(1001, "GENERRAL_ACCOUNT_REGISTER_FAIL_REASON1"),
    GENERAL_LOGIN_FAIL_REASON1(1002, "GENERRAL_LOGIN_FAIL_REASON1"),

    ACCOUNT_REGISTER_FAIL_NULL_EMAIL(2001, "ACCOUNT_REGISTER_FAIL_NULL_EMAIL"),
    ACCOUNT_REGISTER_FAIL_NULL_PASSWORD(2002, "ACCOUNT_REGISTER_FAIL_NULL_PASSWORD"),
    ACCOUNT_REGISTER_FAIL_EMPTY_EMAIL(2003, "ACCOUNT_REGISTER_FAIL_EMPTY_EMAIL"),
    ACCOUNT_REGISTER_FAIL_EMPTY_PASSWORD(2004, "ACCOUNT_REGISTER_FAIL_EMPTY_PASSWORD"),
    ACCOUNT_REGISTER_FAIL_ALREADY_EXIST_EMAIL(2005, "ACCOUNT_REGISTER_FAIL_ALREADY_EXIST_EMAIL"),
    ACCOUNT_REGISTER_FAIL_INVALID_EMAIL_FORMAT(2006, "ACCOUNT_REGISTER_FAIL_INVALID_EMAIL_FORMAT"),
    ACCOUNT_REGISTER_FAIL_EMAIL_TOO_LONG(2007, "ACCOUNT_REGISTER_FAIL_EMAIL_TOO_LONG"),
    ACCOUNT_REGISTER_FAIL_PASSWORD_TOO_SHORT(2008, "ACCOUNT_REGISTER_FAIL_PASSWORD_TOO_SHORT"),
    ACCOUNT_REGISTER_FAIL_PASSWORD_TOO_LONG(2009, "ACCOUNT_REGISTER_FAIL_PASSWORD_TOO_LONG"),
    GET_ALL_CHARACTERS_FAIL_ACCOUNT_NOT_FOUND(2010, "GET_ALL_CHARACTERS_FAIL_ACCOUNT_NOT_FOUND"),

    LOGIN_FAIL_NULL_EMAIL(2051, "LOGIN_FAIL_NULL_EMAIL"),
    LOGIN_FAIL_NULL_PASSWORD(2052, "LOGIN_FAIL_NULL_PASSWORD"),
    LOGIN_FAIL_EMPTY_EMAIL(2053, "LOGIN_FAIL_EMPTY_EMAIL"),
    LOGIN_FAIL_EMPTY_PASSWORD(2054, "LOGIN_FAIL_EMPTY_PASSWORD"),
    LOGIN_FAIL_FIND_BY_EMAIL(2056, "LOGIN_FAIL_FIND_BY_EMAIL"),
    LOGIN_FAIL_MATCH_PASSWORD(2057, "LOGIN_FAIL_MATCH_PASSWORD"),
    LOGIN_FAIL_GOOGLE_NULL_TOKEN(2058, "LOGIN_FAIL_GOOGLE_NULL_TOKEN"),
    LOGIN_FAIL_GOOGLE_NULL_EMAIL(2059, "LOGIN_FAIL_GOOGLE_NULL_EMAIL"),
    LOGIN_FAIL_GOOGLE_NULL_UID(2060, "LOGIN_FAIL_GOOGLE_NULL_UID"),
    LOGIN_FAIL_GOOGLE_NULL_EMAIL_VERIFIED(2061, "LOGIN_FAIL_GOOGLE_NULL_EMAIL_VERIFIED"),
    LOGIN_FAIL_GOOGLE_EMAIL_VERIFIED(2062, "LOGIN_FAIL_GOOGLE_EMAIL_VERIFIED"),
    LOGIN_FAIL_GOOGLE_FIREBASE_AUTH_EXCEPTION(2063, "LOGIN_FAIL_GOOGLE_FIREBASE_AUTH_EXCEPTION"),
    LOGIN_FAIL_GOOGLE_TOKEN_VERIFICATION_EXCEPTION(2064, "LOGIN_FAIL_GOOGLE_TOKEN_VERIFICATION_EXCEPTION"),
    LOGIN_FAIL_GUEST_NULL_ID(2065, "LOGIN_FAIL_GUEST_NULL_ID"),

    REFRESH_TOKEN_FAIL_NULL_TOKEN(2101, "REFRESH_TOKEN_FAIL_NULL_TOKEN"),
    REFRESH_TOKEN_FAIL_EMPTY_TOKEN(2102, "REFRESH_TOKEN_FAIL_EMPTY_TOKEN"),
    REFRESH_TOKEN_FAIL_INVALID_TOKEN(2103, "REFRESH_TOKEN_FAIL_INVALID_TOKEN"),
    REFRESH_TOKEN_FAIL_ACCOUNT_NOT_FOUND(2104, "REFRESH_TOKEN_FAIL_ACCOUNT_NOT_FOUND"),


    CHARACTER_CREATE_FAIL_ACCOUNT_NOT_FOUND(3001, "CHARACTER_CREATE_FAIL_ACCOUNT_NOT_FOUND"),
    CHARACTER_CREATE_FAIL_NAME_DUPLICATE(3002, "CHARACTER_CREATE_FAIL_NAME_DUPLICATE"),

    GET_CHARACTER_INFO_DTO_FAIL_CHARACTER_NOT_FOUND(3101, "GET_CHARACTER_INFO_DTO_FAIL_CHARACTER_NOT_FOUND"),
    UPDATE_MINERAL_FAIL_CHARACTER_NOT_FOUND(3102, "UPDATE_MINERAL_FAIL_CHARACTER_NOT_FOUND"),
    ADD_MINERAL_FAIL_CHARACTER_NOT_FOUND(3103, "ADD_MINERAL_FAIL_CHARACTER_NOT_FOUND"),
    UPDATE_MINERAL_RARE_FAIL_CHARACTER_NOT_FOUND(3104, "UPDATE_MINERAL_RARE_FAIL_CHARACTER_NOT_FOUND"),
    ADD_MINERAL_RARE_FAIL_CHARACTER_NOT_FOUND(3105, "ADD_MINERAL_RARE_FAIL_CHARACTER_NOT_FOUND"),
    UPDATE_MINERAL_EXOTIC_FAIL_CHARACTER_NOT_FOUND(3106, "UPDATE_MINERAL_EXOTIC_FAIL_CHARACTER_NOT_FOUND"),
    ADD_MINERAL_EXOTIC_FAIL_CHARACTER_NOT_FOUND(3107, "ADD_MINERAL_EXOTIC_FAIL_CHARACTER_NOT_FOUND"),
    UPDATE_MINERAL_DARK_FAIL_CHARACTER_NOT_FOUND(3108, "UPDATE_MINERAL_DARK_FAIL_CHARACTER_NOT_FOUND"),
    ADD_MINERAL_DARK_FAIL_CHARACTER_NOT_FOUND(3109, "ADD_MINERAL_DARK_FAIL_CHARACTER_NOT_FOUND"),
    UPDATE_TECH_LEVEL_FAIL_CHARACTER_NOT_FOUND(3110, "UPDATE_TECH_LEVEL_FAIL_CHARACTER_NOT_FOUND"),
    ADD_TECH_LEVEL_FAIL_CHARACTER_NOT_FOUND(3111, "ADD_TECH_LEVEL_FAIL_CHARACTER_NOT_FOUND"),





    FLEET_NOT_FOUND(4001, "Fleet not found"),
    FLEET_DUPLICATE_NAME(4002, "Fleet name already exists"),

    CHARACTER_CONTROLLER_FAIL_NULL_TOKEN(102001, "CHARACTER_CONTROLLER_FAIL_NULL_TOKEN"),
    CHARACTER_CONTROLLER_FAIL_NULL_EMAIL(102002, "CHARACTER_CONTROLLER_FAIL_NULL_EMAIL"),
    CHARACTER_CONTROLLER_FAIL_NULL_ACCOUNTID(102003, "CHARACTER_CONTROLLER_FAIL_NULL_ACCOUNTID"),
    CHARACTER_CONTROLLER_FAIL_INVALID_CHARACTER(102004, "CHARACTER_CONTROLLER_FAIL_INVALID_CHARACTER"),
    CHARACTER_CONTROLLER_FAIL_NULL_ACTIVE_FLEET(102005, "CHARACTER_CONTROLLER_FAIL_NULL_ACTIVE_FLEET"),

    FLEET_CONTROLLER_FAIL_INVALID_TOKEN(103001, "FLEET_CONTROLLER_FAIL_INVALID_TOKEN"),
    FLEET_CONTROLLER_FAIL_JWT_HAS_CHARACTERID(103002, "FLEET_CONTROLLER_FAIL_JWT_HAS_CHARACTERID"),
    FLEET_CONTROLLER_FAIL_JWT_GET_CHARACTERID(103003, "FLEET_CONTROLLER_FAIL_JWT_GET_CHARACTERID"),

    EXECUTE_COMMAND_FAIL_NULL_TOKEN(108001, "EXECUTE_COMMAND_FAIL_NULL_TOKEN"),
    EXECUTE_COMMAND_FAIL_NULL_CHARACTERID(108002, "EXECUTE_COMMAND_FAIL_NULL_CHARACTERID"),
    EXECUTE_COMMAND_FAIL_SETMINERAL_INVALID_PARAM(108003, "EXECUTE_COMMAND_FAIL_SETMINERAL_INVALID_PARAM"),
    EXECUTE_COMMAND_FAIL_SETMINERAL_PARSE_PARAM(108004, "EXECUTE_COMMAND_FAIL_SETMINERAL_PARSE_PARAM"),
    EXECUTE_COMMAND_FAIL_ADDMIKNERAL_INVALID_PARAM(108005, "EXECUTE_COMMAND_FAIL_ADDMIKNERAL_INVALID_PARAM"),
    EXECUTE_COMMAND_FAIL_ADDMIKNERAL_PARSE_PARAM(108006, "EXECUTE_COMMAND_FAIL_ADDMIKNERAL_PARSE_PARAM"),

    EXECUTE_COMMAND_FAIL_SETMINERALRARE_INVALID_PARAM(108010, "EXECUTE_COMMAND_FAIL_SETMINERALRARE_INVALID_PARAM"),
    EXECUTE_COMMAND_FAIL_SETMINERALRARE_PARSE_PARAM(108011, "EXECUTE_COMMAND_FAIL_SETMINERALRARE_PARSE_PARAM"),
    EXECUTE_COMMAND_FAIL_ADDMINERALRARE_INVALID_PARAM(108012, "EXECUTE_COMMAND_FAIL_ADDMINERALRARE_INVALID_PARAM"),
    EXECUTE_COMMAND_FAIL_ADDMINERALRARE_PARSE_PARAM(108013, "EXECUTE_COMMAND_FAIL_ADDMINERALRARE_PARSE_PARAM"),

    EXECUTE_COMMAND_FAIL_SETMINERALEXOTIC_INVALID_PARAM(108020, "EXECUTE_COMMAND_FAIL_SETMINERALEXOTIC_INVALID_PARAM"),
    EXECUTE_COMMAND_FAIL_SETMINERALEXOTIC_PARSE_PARAM(108021, "EXECUTE_COMMAND_FAIL_SETMINERALEXOTIC_PARSE_PARAM"),
    EXECUTE_COMMAND_FAIL_ADDMINERALEXOTIC_INVALID_PARAM(108022, "EXECUTE_COMMAND_FAIL_ADDMINERALEXOTIC_INVALID_PARAM"),
    EXECUTE_COMMAND_FAIL_ADDMINERALEXOTIC_PARSE_PARAM(108023, "EXECUTE_COMMAND_FAIL_ADDMINERALEXOTIC_PARSE_PARAM"),

    EXECUTE_COMMAND_FAIL_SETMINERALDARK_INVALID_PARAM(108030, "EXECUTE_COMMAND_FAIL_SETMINERALDARK_INVALID_PARAM"),
    EXECUTE_COMMAND_FAIL_SETMINERALDARK_PARSE_PARAM(108031, "EXECUTE_COMMAND_FAIL_SETMINERALDARK_PARSE_PARAM"),
    EXECUTE_COMMAND_FAIL_ADDMINERALDARK_INVALID_PARAM(108032, "EXECUTE_COMMAND_FAIL_ADDMINERALDARK_INVALID_PARAM"),
    EXECUTE_COMMAND_FAIL_ADDMINERALDARK_PARSE_PARAM(108033, "EXECUTE_COMMAND_FAIL_ADDMINERALDARK_PARSE_PARAM"),

    EXECUTE_COMMAND_FAIL_ADDTECH_INVALID_PARAM(108040, "EXECUTE_COMMAND_FAIL_ADDTECH_INVALID_PARAM"),
    EXECUTE_COMMAND_FAIL_ADDTECH_PARSE_PARAM(108041, "EXECUTE_COMMAND_FAIL_ADDTECH_PARSE_PARAM"),

    EXECUTE_COMMAND_FAIL_CHANGEFORMATION_INVALID_PARAM(108050, "EXECUTE_COMMAND_FAIL_CHANGEFORMATION_INVALID_PARAM"),
    EXECUTE_COMMAND_FAIL_CHANGEFORMATION_PARSE_PARAM(108051, "EXECUTE_COMMAND_FAIL_CHANGEFORMATION_PARSE_PARAM"),
    EXECUTE_COMMAND_FAIL_CHANGEFORMATION_INVALID_INDEX(108052, "EXECUTE_COMMAND_FAIL_CHANGEFORMATION_INVALID_INDEX"),
    EXECUTE_COMMAND_FAIL_CHANGEFORMATION_INVALID_TYPE(108053, "EXECUTE_COMMAND_FAIL_CHANGEFORMATION_INVALID_TYPE"),

    EXECUTE_COMMAND_FAIL_JSON_SERIALIZE(108060, "EXECUTE_COMMAND_FAIL_JSON_SERIALIZE"),
    EXECUTE_COMMAND_FAIL_UNKNOWN_COMMAND(108099, "EXECUTE_COMMAND_FAIL_UNKNOWN_COMMAND"),



    ADD_SHIP_FAIL_SHIP_NOT_FOUND(109001, "ADD_SHIP_FAIL_SHIP_NOT_FOUND"),
    ADD_SHIP_FAIL_FLEET_NOT_FOUND(109002, "ADD_SHIP_FAIL_FLEET_NOT_FOUND"),
    ADD_SHIP_FAIL_ACTIVE_FLEET_NOT_FOUND(109003, "ADD_SHIP_FAIL_ACTIVE_FLEET_NOT_FOUND"),
    ADD_SHIP_FAIL_FLEET_MAX_SHIPS_REACHED(109004, "ADD_SHIP_FAIL_FLEET_MAX_SHIPS_REACHED"),
    ADD_SHIP_FAIL_INSUFFICIENT_TECH_LEVEL(109005, "ADD_SHIP_FAIL_INSUFFICIENT_TECH_LEVEL"),
    ADD_SHIP_FAIL_INSUFFICIENT_MINERAL(109006, "ADD_SHIP_FAIL_INSUFFICIENT_MINERAL"),
    ADD_SHIP_FAIL_INSUFFICIENT_MINERAL_RARE(109007, "ADD_SHIP_FAIL_INSUFFICIENT_MINERAL_RARE"),
    ADD_SHIP_FAIL_INSUFFICIENT_MINERAL_EXOTIC(109008, "ADD_SHIP_FAIL_INSUFFICIENT_MINERAL_EXOTIC"),
    ADD_SHIP_FAIL_INSUFFICIENT_MINERAL_DARK(109009, "ADD_SHIP_FAIL_INSUFFICIENT_MINERAL_DARK"),


    UNLOCK_MODULE_FAIL_SHIP_NOT_FOUND(110001, "UNLOCK_MODULE_FAIL_SHIP_NOT_FOUND"),
    UNLOCK_MODULE_FAIL_FLEET_ACCESS_DENIED(110002, "UNLOCK_MODULE_FAIL_FLEET_ACCESS_DENIED"),
    UNLOCK_MODULE_FAIL_ALREADY_UNLOCKED(110003, "UNLOCK_MODULE_FAIL_ALREADY_UNLOCKED"),
    UNLOCK_MODULE_FAIL_CHARACTER_NOT_FOUND(110004, "UNLOCK_MODULE_FAIL_CHARACTER_NOT_FOUND"),
    UNLOCK_MODULE_FAIL_INSUFFICIENT_MINERAL(110005, "UNLOCK_MODULE_FAIL_INSUFFICIENT_MINERAL"),
    UNLOCK_MODULE_FAIL_BODY_MODULE_NOT_FOUND(110006, "UNLOCK_MODULE_FAIL_BODY_MODULE_NOT_FOUND"),
    UNLOCK_MODULE_FAIL_BODY_DATA_NOT_FOUND(110007, "UNLOCK_MODULE_FAIL_BODY_DATA_NOT_FOUND"),
    UNLOCK_MODULE_FAIL_SLOT_INDEX_OUT_OF_BOUNDS(110008, "UNLOCK_MODULE_FAIL_SLOT_INDEX_OUT_OF_BOUNDS"),
    UNLOCK_MODULE_FAIL_INVALID_MODULE_TYPE(110009, "UNLOCK_MODULE_FAIL_INVALID_MODULE_TYPE"),

    CHANGE_MODULE_FAIL_SHIP_NOT_FOUND(110101, "CHANGE_MODULE_FAIL_SHIP_NOT_FOUND"),
    CHANGE_MODULE_FAIL_FLEET_ACCESS_DENIED(110102, "CHANGE_MODULE_FAIL_FLEET_ACCESS_DENIED"),
    CHANGE_MODULE_FAIL_SAME_MODULE(110103, "CHANGE_MODULE_FAIL_SAME_MODULE"),
    CHANGE_MODULE_FAIL_NOT_MATCH_MODULE_TYPE(110104, "CHANGE_MODULE_FAIL_NOT_MATCH_MODULE_TYPE"),
    CHANGE_MODULE_FAIL_MODULE_NOT_FOUND(110105, "CHANGE_MODULE_FAIL_MODULE_NOT_FOUND"),
    CHANGE_MODULE_FAIL_MODULE_WEAPON_NOT_FOUND(110106, "CHANGE_MODULE_FAIL_MODULE_WEAPON_NOT_FOUND"),
    CHANGE_MODULE_FAIL_NOT_RESEARCHED(110107, "CHANGE_MODULE_FAIL_NOT_RESEARCHED"),

    CHANGE_BODY_FAIL_SHIP_NOT_FOUND(110151, "CHANGE_BODY_FAIL_SHIP_NOT_FOUND"),
    CHANGE_BODY_FAIL_FLEET_ACCESS_DENIED(110152, "CHANGE_BODY_FAIL_FLEET_ACCESS_DENIED"),
    CHANGE_BODY_FAIL_SAME_BODY(110153, "CHANGE_BODY_FAIL_SAME_BODY"),
    CHANGE_BODY_FAIL_BODY_MODULE_NOT_FOUND(110154, "CHANGE_BODY_FAIL_BODY_MODULE_NOT_FOUND"),
    CHANGE_BODY_FAIL_NOT_RESEARCHED(110155, "CHANGE_BODY_FAIL_NOT_RESEARCHED"),
    CHANGE_BODY_FAIL_NEW_BODY_DATA_NOT_FOUND(110156, "CHANGE_BODY_FAIL_NEW_BODY_DATA_NOT_FOUND"),

    RESEARCH_MODULE_FAIL_ALREADY_RESEARCHED(110201, "RESEARCH_MODULE_FAIL_ALREADY_RESEARCHED"),
    RESEARCH_MODULE_FAIL_CHARACTER_NOT_FOUND(110202, "RESEARCH_MODULE_FAIL_CHARACTER_NOT_FOUND"),
    RESEARCH_MODULE_FAIL_INSUFFICIENT_TECH_LEVEL(110203, "RESEARCH_MODULE_FAIL_INSUFFICIENT_TECH_LEVEL"),
    RESEARCH_MODULE_FAIL_INSUFFICIENT_MINERAL(110204, "RESEARCH_MODULE_FAIL_INSUFFICIENT_MINERAL"),

    RESEARCH_MODULE_FAIL_INSUFFICIENT_MINERAL_RARE(110205, "RESEARCH_MODULE_FAIL_INSUFFICIENT_MINERAL_RARE"),
    RESEARCH_MODULE_FAIL_INSUFFICIENT_MINERAL_EXOTIC(110206, "RESEARCH_MODULE_FAIL_INSUFFICIENT_MINERAL_EXOTIC"),
    RESEARCH_MODULE_FAIL_INSUFFICIENT_MINERAL_DARK(110207, "RESEARCH_MODULE_FAIL_INSUFFICIENT_MINERAL_DARK"),

    UPGRADE_MODULE_FAIL_SHIP_NOT_FOUND(110301, "UPGRADE_MODULE_FAIL_SHIP_NOT_FOUND"),
    UPGRADE_MODULE_FAIL_FLEET_ACCESS_DENIED(110302, "UPGRADE_MODULE_FAIL_FLEET_ACCESS_DENIED"),
    UPGRADE_MODULE_FAIL_MODULE_NOT_FOUND(110303, "UPGRADE_MODULE_FAIL_MODULE_NOT_FOUND"),
    UPGRADE_MODULE_FAIL_MODULE_LEVEL_MISMATCH(110304, "UPGRADE_MODULE_FAIL_MODULE_LEVEL_MISMATCH"),
    UPGRADE_MODULE_FAIL_CHARACTER_NOT_FOUND(110305, "UPGRADE_MODULE_FAIL_CHARACTER_NOT_FOUND"),
    UPGRADE_MODULE_FAIL_MODULE_DATA_NOT_FOUND(110306, "UPGRADE_MODULE_FAIL_MODULE_DATA_NOT_FOUND"),

    UPGRADE_MODULE_FAIL_INSUFFICIENT_TECH_LEVEL(110307, "UPGRADE_MODULE_FAIL_INSUFFICIENT_TECH_LEVEL"),
    UPGRADE_MODULE_FAIL_INSUFFICIENT_MINERAL(110308, "UPGRADE_MODULE_FAIL_INSUFFICIENT_MINERAL"),
    UPGRADE_MODULE_FAIL_INSUFFICIENT_MINERAL_RARE(110309, "UPGRADE_MODULE_FAIL_INSUFFICIENT_MINERAL_RARE"),
    UPGRADE_MODULE_FAIL_INSUFFICIENT_MINERAL_EXOTIC(110310, "UPGRADE_MODULE_FAIL_INSUFFICIENT_MINERAL_EXOTIC"),
    UPGRADE_MODULE_FAIL_INSUFFICIENT_MINERAL_DARK(110311, "UPGRADE_MODULE_FAIL_INSUFFICIENT_MINERAL_DARK"),

    ZONE_CONTROLLER_FAIL_INVALID_TOKEN(111001, "ZONE_CONTROLLER_FAIL_INVALID_TOKEN"),
    ZONE_CONTROLLER_FAIL_JWT_HAS_CHARACTERID(111002, "ZONE_CONTROLLER_FAIL_JWT_HAS_CHARACTERID"),
    ZONE_CONTROLLER_FAIL_JWT_GET_CHARACTERID(111003, "ZONE_CONTROLLER_FAIL_JWT_GET_CHARACTERID"),
    ZONE_CLEAR_FAIL_CHARACTER_NOT_FOUND(111101, "ZONE_CLEAR_FAIL_CHARACTER_NOT_FOUND"),
    ZONE_COLLECT_FAIL_NO_CLEARED_ZONE(111201, "ZONE_COLLECT_FAIL_NO_CLEARED_ZONE"),
    ZONE_COLLECT_FAIL_INVALID_ZONE(111202, "ZONE_COLLECT_FAIL_INVALID_ZONE"),
    ZONE_KILL_FAIL_CHARACTER_NOT_FOUND(111301, "ZONE_KILL_FAIL_CHARACTER_NOT_FOUND"),
    HEARTBEAT_FAIL_CHARACTER_NOT_FOUND(111401, "HEARTBEAT_FAIL_CHARACTER_NOT_FOUND"),

    PROGRESS_CONTROLLER_FAIL_INVALID_TOKEN(112001, "PROGRESS_CONTROLLER_FAIL_INVALID_TOKEN"),
    PROGRESS_CONTROLLER_FAIL_JWT_HAS_CHARACTERID(112002, "PROGRESS_CONTROLLER_FAIL_JWT_HAS_CHARACTERID"),
    PROGRESS_CONTROLLER_FAIL_JWT_GET_CHARACTERID(112003, "PROGRESS_CONTROLLER_FAIL_JWT_GET_CHARACTERID"),

    PVP_CONTROLLER_FAIL_INVALID_TOKEN(113001, "PVP_CONTROLLER_FAIL_INVALID_TOKEN"),
    PVP_CONTROLLER_FAIL_JWT_HAS_CHARACTERID(113002, "PVP_CONTROLLER_FAIL_JWT_HAS_CHARACTERID"),
    PVP_CONTROLLER_FAIL_JWT_GET_CHARACTERID(113003, "PVP_CONTROLLER_FAIL_JWT_GET_CHARACTERID"),
    PVP_REFRESH_LIMIT_EXCEEDED(113101, "PVP_REFRESH_LIMIT_EXCEEDED"),
    PVP_OPPONENT_FLEET_NOT_FOUND(113201, "PVP_OPPONENT_FLEET_NOT_FOUND"),
    PVP_BATTLE_TOKEN_INVALID(113301, "PVP_BATTLE_TOKEN_INVALID"),







    CLIENT_REFRESH_TOKEN_NULL(500001, "CLIENT_REFRESH_TOKEN_NULL"),
    CLIENT_RUNASYNC_FAIL_UNKONW(500002, "CLIENT_RUNASYNC_FAIL_UNKONW"),
    CLIENT_LOGIN_GOOGLE_FAIL_AUTHENTICATION_TIMEOUT(501101, "LOGIN_GOOGLE_FAIL_AUTHENTICATION_TIMEOUT"),
    CLIENT_LOGIN_GOOGLE_FAIL_EXTRACT_AUTHENTICATION(501102, "LOGIN_GOOGLE_FAIL_EXTRACT_AUTHENTICATION"),
    CLIENT_CanAddShip_CHARACTER_NOT_FOUND(510001, "CLIENT_CanAddShip_CHARACTER_NOT_FOUND"),
    CLIENT_CanAddShip_FLEET_MAX_SHIPS_REACHED(510002, "CLIENT_CanAddShip_FLEET_MAX_SHIPS_REACHED"),
    CLIENT_CanAddShip_INSUFFICIENT_TECH_LEVEL(510003, "CLIENT_CanAddShip_INSUFFICIENT_TECH_LEVEL"),
    CLIENT_CanAddShip_INSUFFICIENT_MINERAL(510004, "CLIENT_CanAddShip_INSUFFICIENT_MINERAL"),
    CLIENT_CanAddShip_INSUFFICIENT_MINERAL_RARE(510005, "CLIENT_CanAddShip_INSUFFICIENT_MINERAL_RARE"),
    CLIENT_CanAddShip_INSUFFICIENT_MINERAL_EXOTIC(510006, "CLIENT_CanAddShip_INSUFFICIENT_MINERAL_EXOTIC"),
    CLIENT_CanAddShip_INSUFFICIENT_MINERAL_DARK(510007, "CLIENT_CanAddShip_INSUFFICIENT_MINERAL_DARK"),





    INVALID_DATA_TABLE(5001, "Invalid data table provided"),
    UNKNOWN_ERROR(Integer.MAX_VALUE, "Unknown error");

    private final int code;
    private final String message;

    ServerErrorCode(int code, String message) {
        this.code = code;
        this.message = message;
    }

    public int getCode() {
        return code;
    }

    public String getMessage() {
        return message;
    }
}
