package com.bk.sbs.exception;

public enum ServerErrorCode {
    SUCCESS(0, "Success"),

    HTTP_BAD_REQUEST_400(400, "HTTP_BAD_REQUEST_400"),     // 잘못된 요청
    HTTP_UNAUTHORIZED_401(401, "HTTP_UNAUTHORIZED_401"),    // 인증 안됨
    HTTP_FORBIDDEN_403(403, "HTTP_FORBIDDEN_403"),       // 권한 없음
    HTTP_NOT_FOUND_404(404, "HTTP_NOT_FOUND_404"),       // 서버 찾을 수 없음
    HTTP_SERVER_ERROR_500(500, "HTTP_SERVER_ERROR_500"),    // 서버 에러

    ACCOUNT_REGISTER_FAIL_REASON1(1001, "Account registration failed due to duplicate email"),
    LOGIN_FAIL_REASON1(1002, "Invalid email or password"),
    ACCOUNT_NOT_FOUND(1003, "Account not found"),

    ACCOUNT_REGISTER_FAIL_NULL_EMAIL(2001, "ACCOUNT_REGISTER_FAIL_NULL_EMAIL"),
    ACCOUNT_REGISTER_FAIL_NULL_PASSWORD(2002, "ACCOUNT_REGISTER_FAIL_NULL_PASSWORD"),
    ACCOUNT_REGISTER_FAIL_EMPTY_EMAIL(2003, "ACCOUNT_REGISTER_FAIL_EMPTY_EMAIL"),
    ACCOUNT_REGISTER_FAIL_EMPTY_PASSWORD(2004, "ACCOUNT_REGISTER_FAIL_EMPTY_PASSWORD"),
    ACCOUNT_REGISTER_FAIL_ALREADY_EXIST_EMAIL(2005, "ACCOUNT_REGISTER_FAIL_ALREADY_EXIST_EMAIL"),
    ACCOUNT_REGISTER_FAIL_INVALID_EMAIL_FORMAT(2006, "ACCOUNT_REGISTER_FAIL_INVALID_EMAIL_FORMAT"),
    ACCOUNT_REGISTER_FAIL_EMAIL_TOO_LONG(2007, "ACCOUNT_REGISTER_FAIL_EMAIL_TOO_LONG"),
    ACCOUNT_REGISTER_FAIL_PASSWORD_TOO_SHORT(2008, "ACCOUNT_REGISTER_FAIL_PASSWORD_TOO_SHORT"),
    ACCOUNT_REGISTER_FAIL_PASSWORD_TOO_LONG(2009, "ACCOUNT_REGISTER_FAIL_PASSWORD_TOO_LONG"),

    LOGIN_FAIL_NULL_EMAIL(2051, "LOGIN_FAIL_NULL_EMAIL"),
    LOGIN_FAIL_NULL_PASSWORD(2052, "LOGIN_FAIL_NULL_PASSWORD"),
    LOGIN_FAIL_EMPTY_EMAIL(2053, "LOGIN_FAIL_EMPTY_EMAIL"),
    LOGIN_FAIL_EMPTY_PASSWORD(2054, "LOGIN_FAIL_EMPTY_PASSWORD"),

    REFRESH_TOKEN_FAIL_NULL_TOKEN(2101, "REFRESH_TOKEN_FAIL_NULL_TOKEN"),
    REFRESH_TOKEN_FAIL_EMPTY_TOKEN(2102, "REFRESH_TOKEN_FAIL_EMPTY_TOKEN"),
    REFRESH_TOKEN_FAIL_INVALID_TOKEN(2103, "REFRESH_TOKEN_FAIL_INVALID_TOKEN"),
    REFRESH_TOKEN_FAIL_ACCOUNT_NOT_FOUND(2104, "REFRESH_TOKEN_FAIL_ACCOUNT_NOT_FOUND"),

    CHARACTER_CREATE_FAIL_REASON1(3001, "Character creation failed"),
    CHARACTER_NAME_DUPLICATE(3002, "Character name already exists"),
    CHARACTER_NOT_FOUND(3004, "Character not found"),
    FLEET_NOT_FOUND(4001, "Fleet not found"),
    FLEET_DUPLICATE_NAME(4002, "Fleet name already exists"),



    FLEET_CONTROLLER_FAIL_INVALID_TOKEN(103001, "FLEET_CONTROLLER_FAIL_INVALID_TOKEN"),
    FLEET_CONTROLLER_FAIL_JWT_HAS_CHARACTERID(103002, "FLEET_CONTROLLER_FAIL_JWT_HAS_CHARACTERID"),
    FLEET_CONTROLLER_FAIL_JWT_GET_CHARACTERID(103003, "FLEET_CONTROLLER_FAIL_JWT_GET_CHARACTERID"),


    ADD_SHIP_FAIL_SHIP_NOT_FOUND(109001, "ADD_SHIP_FAIL_SHIP_NOT_FOUND"),
    ADD_SHIP_FAIL_FLEET_NOT_FOUND(109002, "ADD_SHIP_FAIL_FLEET_NOT_FOUND"),
    ADD_SHIP_FAIL_ACTIVE_FLEET_NOT_FOUND(109003, "ADD_SHIP_FAIL_ACTIVE_FLEET_NOT_FOUND"),
    ADD_SHIP_FAIL_FLEET_MAX_SHIPS_REACHED(109004, "ADD_SHIP_FAIL_FLEET_MAX_SHIPS_REACHED"),
    ADD_SHIP_FAIL_INSUFFICIENT_TECH_LEVEL(109005, "ADD_SHIP_FAIL_INSUFFICIENT_TECH_LEVEL"),
    ADD_SHIP_FAIL_INSUFFICIENT_MINERAL(109006, "ADD_SHIP_FAIL_INSUFFICIENT_MINERAL"),
    ADD_SHIP_FAIL_INSUFFICIENT_MINERAL_RARE(109007, "ADD_SHIP_FAIL_INSUFFICIENT_MINERAL_RARE"),
    ADD_SHIP_FAIL_INSUFFICIENT_MINERAL_EXOTIC(109008, "ADD_SHIP_FAIL_INSUFFICIENT_MINERAL_EXOTIC"),
    ADD_SHIP_FAIL_INSUFFICIENT_MINERAL_DARK(109009, "ADD_SHIP_FAIL_INSUFFICIENT_MINERAL_DARK"),


    UNLOCK_MODULE_FAIL_SHIP_NOT_FOUND(110001, "UNLOCK_MODULE_FAIL_SHIP_NOT_FOUND"),
    UNLOCK_MODULE_FAIL_FLEET_ACCESS_DENIED(110002, "UNLOCK_MODULE_FAIL_FLEET_ACCESS_DENIED"),
    UNLOCK_MODULE_FAIL_ALREADY_UNLOCKED(110003, "UNLOCK_MODULE_FAIL_ALREADY_UNLOCKED"),
    UNLOCK_MODULE_FAIL_CHARACTER_NOT_FOUND(110004, "UNLOCK_MODULE_FAIL_CHARACTER_NOT_FOUND"),
    UNLOCK_MODULE_FAIL_INSUFFICIENT_MINERAL(110005, "UNLOCK_MODULE_FAIL_INSUFFICIENT_MINERAL"),

    CHANGE_MODULE_FAIL_SHIP_NOT_FOUND(110101, "CHANGE_MODULE_FAIL_SHIP_NOT_FOUND"),
    CHANGE_MODULE_FAIL_FLEET_ACCESS_DENIED(110102, "CHANGE_MODULE_FAIL_FLEET_ACCESS_DENIED"),
    CHANGE_MODULE_FAIL_SAME_MODULE(110103, "CHANGE_MODULE_FAIL_SAME_MODULE"),
    CHANGE_MODULE_FAIL_NOT_MATCH_MODULE_TYPE(110104, "CHANGE_MODULE_FAIL_NOT_MATCH_MODULE_TYPE"),
    CHANGE_MODULE_FAIL_MODULE_NOT_FOUND(110105, "CHANGE_MODULE_FAIL_MODULE_NOT_FOUND"),
    CHANGE_MODULE_FAIL_MODULE_WEAPON_NOT_FOUND(110106, "CHANGE_MODULE_FAIL_MODULE_WEAPON_NOT_FOUND"),
    CHANGE_MODULE_FAIL_NOT_RESEARCHED(110107, "CHANGE_MODULE_FAIL_NOT_RESEARCHED"),

    RESEARCH_MODULE_FAIL_ALREADY_RESEARCHED(110201, "RESEARCH_MODULE_FAIL_ALREADY_RESEARCHED"),
    RESEARCH_MODULE_FAIL_CHARACTER_NOT_FOUND(110202, "RESEARCH_MODULE_FAIL_CHARACTER_NOT_FOUND"),
    RESEARCH_MODULE_FAIL_INSUFFICIENT_TECH_LEVEL(110203, "RESEARCH_MODULE_FAIL_INSUFFICIENT_TECH_LEVEL"),
    RESEARCH_MODULE_FAIL_INSUFFICIENT_MINERAL(110204, "RESEARCH_MODULE_FAIL_INSUFFICIENT_MINERAL"),

    RESEARCH_MODULE_FAIL_INSUFFICIENT_MINERAL_RARE(110205, "RESEARCH_MODULE_FAIL_INSUFFICIENT_MINERAL_RARE"),
    RESEARCH_MODULE_FAIL_INSUFFICIENT_MINERAL_EXOTIC(110206, "RESEARCH_MODULE_FAIL_INSUFFICIENT_MINERAL_EXOTIC"),
    RESEARCH_MODULE_FAIL_INSUFFICIENT_MINERAL_DARK(110207, "RESEARCH_MODULE_FAIL_INSUFFICIENT_MINERAL_DARK"),

    UPGRADE_MODULE_FAIL_SHIP_NOT_FOUND(110301, "UPGRADE_MODULE_FAIL_SHIP_NOT_FOUND"),
    UPGRADE_MODULE_FAIL_FLEET_ACCESS_DENIED(110302, "UPGRADE_MODULE_FAIL_FLEET_ACCESS_DENIED"),
    UPGRADE_MODULE_FAIL_MODULE_NOT_FOUND(110303, "UPGRADE_MODULE_FAIL_MODULE_NOT_FOUND"),
    UPGRADE_MODULE_FAIL_MODULE_LEVEL_MISMATCH(110304, "UPGRADE_MODULE_FAIL_MODULE_LEVEL_MISMATCH"),
    UPGRADE_MODULE_FAIL_CHARACTER_NOT_FOUND(110305, "UPGRADE_MODULE_FAIL_CHARACTER_NOT_FOUND"),
    UPGRADE_MODULE_FAIL_MODULE_DATA_NOT_FOUND(110306, "UPGRADE_MODULE_FAIL_MODULE_DATA_NOT_FOUND"),

    UPGRADE_MODULE_FAIL_INSUFFICIENT_TECH_LEVEL(110307, "UPGRADE_MODULE_FAIL_INSUFFICIENT_TECH_LEVEL"),
    UPGRADE_MODULE_FAIL_INSUFFICIENT_MINERAL(110308, "UPGRADE_MODULE_FAIL_INSUFFICIENT_MINERAL"),
    UPGRADE_MODULE_FAIL_INSUFFICIENT_MINERAL_RARE(110309, "UPGRADE_MODULE_FAIL_INSUFFICIENT_MINERAL_RARE"),
    UPGRADE_MODULE_FAIL_INSUFFICIENT_MINERAL_EXOTIC(110310, "UPGRADE_MODULE_FAIL_INSUFFICIENT_MINERAL_EXOTIC"),
    UPGRADE_MODULE_FAIL_INSUFFICIENT_MINERAL_DARK(110311, "UPGRADE_MODULE_FAIL_INSUFFICIENT_MINERAL_DARK"),










    CLIENT_REFRESH_TOKEN_NULL(500001, "CLIENT_REFRESH_TOKEN_NULL"),
    CLIENT_RUNASYNC_FAIL_UNKONW(500002, "CLIENT_RUNASYNC_FAIL_UNKONW"),
    CLIENT_LOGIN_GOOGLE_FAIL_AUTHENTICATION_TIMEOUT(501101, "LOGIN_GOOGLE_FAIL_AUTHENTICATION_TIMEOUT"),
    CLIENT_LOGIN_GOOGLE_FAIL_EXTRACT_AUTHENTICATION(501102, "LOGIN_GOOGLE_FAIL_EXTRACT_AUTHENTICATION"),
    CLIENT_CanAddShip_FLEET_MAX_SHIPS_REACHED(510001, "CLIENT_CanAddShip_FLEET_MAX_SHIPS_REACHED"),
    CLIENT_CanAddShip_INSUFFICIENT_TECH_LEVEL(510002, "CLIENT_CanAddShip_INSUFFICIENT_TECH_LEVEL"),
    CLIENT_CanAddShip_INSUFFICIENT_MINERAL(510003, "CLIENT_CanAddShip_INSUFFICIENT_MINERAL"),
    CLIENT_CanAddShip_INSUFFICIENT_MINERAL_RARE(510004, "CLIENT_CanAddShip_INSUFFICIENT_MINERAL_RARE"),
    CLIENT_CanAddShip_INSUFFICIENT_MINERAL_EXOTIC(510005, "CLIENT_CanAddShip_INSUFFICIENT_MINERAL_EXOTIC"),
    CLIENT_CanAddShip_INSUFFICIENT_MINERAL_DARK(510006, "CLIENT_CanAddShip_INSUFFICIENT_MINERAL_DARK"),




    INVALID_DATA_TABLE(5001, "Invalid data table provided"),
    UNKNOWN_ERROR(Integer.MAX_VALUE, "Unknown error");

    private final int code;
    private final String message;

    ServerErrorCode(int code, String message) {
        this.code = code;
        this.message = message;
    }

    public int getCode() {
        return code;
    }

    public String getMessage() {
        return message;
    }
}
