package com.bk.sbs.exception;

public enum ServerErrorCode {
    SUCCESS(0, "Success"),

    HTTP_BAD_REQUEST_400(400, "HTTP_BAD_REQUEST_400"),     // 잘못된 요청
    HTTP_UNAUTHORIZED_401(401, "HTTP_UNAUTHORIZED_401"),    // 인증 안됨
    HTTP_FORBIDDEN_403(403, "HTTP_FORBIDDEN_403"),       // 권한 없음
    HTTP_NOT_FOUND_404(404, "HTTP_NOT_FOUND_404"),       // 서버 찾을 수 없음
    HTTP_SERVER_ERROR_500(500, "HTTP_SERVER_ERROR_500"),    // 서버 에러

    GENERAL_ACCOUNT_REGISTER_FAIL_REASON1(1001, "GENERRAL_ACCOUNT_REGISTER_FAIL_REASON1"),
    GENERAL_LOGIN_FAIL_REASON1(1002, "GENERRAL_LOGIN_FAIL_REASON1"),

    ACCOUNT_REGISTER_FAIL_NULL_EMAIL(2001, "ACCOUNT_REGISTER_FAIL_NULL_EMAIL"),
    ACCOUNT_REGISTER_FAIL_NULL_PASSWORD(2002, "ACCOUNT_REGISTER_FAIL_NULL_PASSWORD"),
    ACCOUNT_REGISTER_FAIL_EMPTY_EMAIL(2003, "ACCOUNT_REGISTER_FAIL_EMPTY_EMAIL"),
    ACCOUNT_REGISTER_FAIL_EMPTY_PASSWORD(2004, "ACCOUNT_REGISTER_FAIL_EMPTY_PASSWORD"),
    ACCOUNT_REGISTER_FAIL_ALREADY_EXIST_EMAIL(2005, "ACCOUNT_REGISTER_FAIL_ALREADY_EXIST_EMAIL"),
    ACCOUNT_REGISTER_FAIL_INVALID_EMAIL_FORMAT(2006, "ACCOUNT_REGISTER_FAIL_INVALID_EMAIL_FORMAT"),
    ACCOUNT_REGISTER_FAIL_EMAIL_TOO_LONG(2007, "ACCOUNT_REGISTER_FAIL_EMAIL_TOO_LONG"),
    ACCOUNT_REGISTER_FAIL_PASSWORD_TOO_SHORT(2008, "ACCOUNT_REGISTER_FAIL_PASSWORD_TOO_SHORT"),
    ACCOUNT_REGISTER_FAIL_PASSWORD_TOO_LONG(2009, "ACCOUNT_REGISTER_FAIL_PASSWORD_TOO_LONG"),
    GET_ALL_COMMANDERS_FAIL_ACCOUNT_NOT_FOUND(2010, "GET_ALL_COMMANDERS_FAIL_ACCOUNT_NOT_FOUND"),

    LOGIN_FAIL_NULL_EMAIL(2051, "LOGIN_FAIL_NULL_EMAIL"),
    LOGIN_FAIL_NULL_PASSWORD(2052, "LOGIN_FAIL_NULL_PASSWORD"),
    LOGIN_FAIL_EMPTY_EMAIL(2053, "LOGIN_FAIL_EMPTY_EMAIL"),
    LOGIN_FAIL_EMPTY_PASSWORD(2054, "LOGIN_FAIL_EMPTY_PASSWORD"),
    LOGIN_FAIL_FIND_BY_EMAIL(2056, "LOGIN_FAIL_FIND_BY_EMAIL"),
    LOGIN_FAIL_MATCH_PASSWORD(2057, "LOGIN_FAIL_MATCH_PASSWORD"),
    LOGIN_FAIL_GOOGLE_NULL_TOKEN(2058, "LOGIN_FAIL_GOOGLE_NULL_TOKEN"),
    LOGIN_FAIL_GOOGLE_NULL_EMAIL(2059, "LOGIN_FAIL_GOOGLE_NULL_EMAIL"),
    LOGIN_FAIL_GOOGLE_NULL_UID(2060, "LOGIN_FAIL_GOOGLE_NULL_UID"),
    LOGIN_FAIL_GOOGLE_NULL_EMAIL_VERIFIED(2061, "LOGIN_FAIL_GOOGLE_NULL_EMAIL_VERIFIED"),
    LOGIN_FAIL_GOOGLE_EMAIL_VERIFIED(2062, "LOGIN_FAIL_GOOGLE_EMAIL_VERIFIED"),
    LOGIN_FAIL_GOOGLE_FIREBASE_AUTH_EXCEPTION(2063, "LOGIN_FAIL_GOOGLE_FIREBASE_AUTH_EXCEPTION"),
    LOGIN_FAIL_GOOGLE_TOKEN_VERIFICATION_EXCEPTION(2064, "LOGIN_FAIL_GOOGLE_TOKEN_VERIFICATION_EXCEPTION"),
    LOGIN_FAIL_GUEST_NULL_ID(2065, "LOGIN_FAIL_GUEST_NULL_ID"),
    LINK_GOOGLE_FAIL_ALREADY_LINKED(2070, "LINK_GOOGLE_FAIL_ALREADY_LINKED"),
    LINK_GOOGLE_FAIL_GOOGLE_ID_ALREADY_USED(2071, "LINK_GOOGLE_FAIL_GOOGLE_ID_ALREADY_USED"),
    UNLINK_GOOGLE_FAIL_NOT_LINKED(2075, "UNLINK_GOOGLE_FAIL_NOT_LINKED"),

    REFRESH_TOKEN_FAIL_NULL_TOKEN(2101, "REFRESH_TOKEN_FAIL_NULL_TOKEN"),
    REFRESH_TOKEN_FAIL_EMPTY_TOKEN(2102, "REFRESH_TOKEN_FAIL_EMPTY_TOKEN"),
    REFRESH_TOKEN_FAIL_INVALID_TOKEN(2103, "REFRESH_TOKEN_FAIL_INVALID_TOKEN"),
    REFRESH_TOKEN_FAIL_INVALID_TOKEN2(2104, "REFRESH_TOKEN_FAIL_INVALID_TOKEN2"),
    REFRESH_TOKEN_FAIL_ACCOUNT_NOT_FOUND(2105, "REFRESH_TOKEN_FAIL_ACCOUNT_NOT_FOUND"),


    COMMANDER_CREATE_FAIL_ACCOUNT_NOT_FOUND(3001, "COMMANDER_CREATE_FAIL_ACCOUNT_NOT_FOUND"),
    COMMANDER_CREATE_FAIL_NAME_DUPLICATE(3002, "COMMANDER_CREATE_FAIL_NAME_DUPLICATE"),

    GET_COMMANDER_INFO_DTO_FAIL_COMMANDER_NOT_FOUND(3101, "GET_COMMANDER_INFO_DTO_FAIL_COMMANDER_NOT_FOUND"),
    UPDATE_MINERAL_FAIL_COMMANDER_NOT_FOUND(3102, "UPDATE_MINERAL_FAIL_COMMANDER_NOT_FOUND"),
    ADD_MINERAL_FAIL_COMMANDER_NOT_FOUND(3103, "ADD_MINERAL_FAIL_COMMANDER_NOT_FOUND"),

    COMMANDER_RENAME_FAIL_COMMANDER_NOT_FOUND(3201, "COMMANDER_RENAME_FAIL_COMMANDER_NOT_FOUND"),
    COMMANDER_RENAME_FAIL_NAME_DUPLICATE(3202, "COMMANDER_RENAME_FAIL_NAME_DUPLICATE"),
    COMMANDER_RENAME_FAIL_INVALID_NAME(3203, "COMMANDER_RENAME_FAIL_INVALID_NAME"),
    COMMANDER_RENAME_FAIL_PROFANITY(3204, "COMMANDER_RENAME_FAIL_PROFANITY"),
    COMMANDER_RENAME_FAIL_NO_REMAINING_COUNT(3205, "COMMANDER_RENAME_FAIL_NO_REMAINING_COUNT"),

    COMMANDER_VALIDATE_NAME_DUPLICATE(3251, "COMMANDER_VALIDATE_NAME_DUPLICATE"),
    COMMANDER_VALIDATE_NAME_PROFANITY(3252, "COMMANDER_VALIDATE_NAME_PROFANITY"),
    COMMANDER_VALIDATE_NAME_INVALID_FORMAT(3253, "COMMANDER_VALIDATE_NAME_INVALID_FORMAT"),



    FLEET_NOT_FOUND(4001, "Fleet not found"),
    FLEET_DUPLICATE_NAME(4002, "Fleet name already exists"),

    COMMANDER_CONTROLLER_FAIL_NULL_TOKEN(102001, "COMMANDER_CONTROLLER_FAIL_NULL_TOKEN"),
    COMMANDER_CONTROLLER_FAIL_NULL_EMAIL(102002, "COMMANDER_CONTROLLER_FAIL_NULL_EMAIL"),
    COMMANDER_CONTROLLER_FAIL_NULL_ACCOUNTID(102003, "COMMANDER_CONTROLLER_FAIL_NULL_ACCOUNTID"),
    COMMANDER_CONTROLLER_FAIL_INVALID_COMMANDER(102004, "COMMANDER_CONTROLLER_FAIL_INVALID_COMMANDER"),
    COMMANDER_CONTROLLER_FAIL_NULL_ACTIVE_FLEET(102005, "COMMANDER_CONTROLLER_FAIL_NULL_ACTIVE_FLEET"),

    FLEET_CONTROLLER_FAIL_INVALID_TOKEN(103001, "FLEET_CONTROLLER_FAIL_INVALID_TOKEN"),
    FLEET_CONTROLLER_FAIL_JWT_HAS_COMMANDERID(103002, "FLEET_CONTROLLER_FAIL_JWT_HAS_COMMANDERID"),
    FLEET_CONTROLLER_FAIL_JWT_GET_COMMANDERID(103003, "FLEET_CONTROLLER_FAIL_JWT_GET_COMMANDERID"),

    EXECUTE_COMMAND_FAIL_NULL_TOKEN(108001, "EXECUTE_COMMAND_FAIL_NULL_TOKEN"),
    EXECUTE_COMMAND_FAIL_NULL_COMMANDERID(108002, "EXECUTE_COMMAND_FAIL_NULL_COMMANDERID"),
    EXECUTE_COMMAND_FAIL_SETMINERAL_INVALID_PARAM(108003, "EXECUTE_COMMAND_FAIL_SETMINERAL_INVALID_PARAM"),
    EXECUTE_COMMAND_FAIL_SETMINERAL_PARSE_PARAM(108004, "EXECUTE_COMMAND_FAIL_SETMINERAL_PARSE_PARAM"),
    EXECUTE_COMMAND_FAIL_ADDMIKNERAL_INVALID_PARAM(108005, "EXECUTE_COMMAND_FAIL_ADDMIKNERAL_INVALID_PARAM"),
    EXECUTE_COMMAND_FAIL_ADDMIKNERAL_PARSE_PARAM(108006, "EXECUTE_COMMAND_FAIL_ADDMIKNERAL_PARSE_PARAM"),
    EXECUTE_COMMAND_FAIL_ADDMINERALS_INVALID_PARAM(108007, "EXECUTE_COMMAND_FAIL_ADDMINERALS_INVALID_PARAM"),
    EXECUTE_COMMAND_FAIL_ADDPVPMINERAL_PARSE_PARAM(108008, "EXECUTE_COMMAND_FAIL_ADDPVPMINERAL_PARSE_PARAM"),
    EXECUTE_COMMAND_FAIL_ADDTEMPMINERAL_PARSE_PARAM(108009, "EXECUTE_COMMAND_FAIL_ADDTEMPMINERAL_PARSE_PARAM"),

    EXECUTE_COMMAND_FAIL_CHANGEFORMATION_INVALID_PARAM(108050, "EXECUTE_COMMAND_FAIL_CHANGEFORMATION_INVALID_PARAM"),
    EXECUTE_COMMAND_FAIL_CHANGEFORMATION_PARSE_PARAM(108051, "EXECUTE_COMMAND_FAIL_CHANGEFORMATION_PARSE_PARAM"),
    EXECUTE_COMMAND_FAIL_CHANGEFORMATION_INVALID_INDEX(108052, "EXECUTE_COMMAND_FAIL_CHANGEFORMATION_INVALID_INDEX"),
    EXECUTE_COMMAND_FAIL_CHANGEFORMATION_INVALID_TYPE(108053, "EXECUTE_COMMAND_FAIL_CHANGEFORMATION_INVALID_TYPE"),

    EXECUTE_COMMAND_FAIL_JSON_SERIALIZE(108060, "EXECUTE_COMMAND_FAIL_JSON_SERIALIZE"),
    EXECUTE_COMMAND_FAIL_UNKNOWN_COMMAND(108099, "EXECUTE_COMMAND_FAIL_UNKNOWN_COMMAND"),



    FLEET_INSTANT_REPAIR_FAIL_COMMANDER_NOT_FOUND(108901, "FLEET_INSTANT_REPAIR_FAIL_COMMANDER_NOT_FOUND"),
    FLEET_INSTANT_REPAIR_FAIL_FLEET_NOT_FOUND(108902, "FLEET_INSTANT_REPAIR_FAIL_FLEET_NOT_FOUND"),
    FLEET_INSTANT_REPAIR_FAIL_INSUFFICIENT_MINERAL(108903, "FLEET_INSTANT_REPAIR_FAIL_INSUFFICIENT_MINERAL"),

    ADD_SHIP_FAIL_SHIP_NOT_FOUND(109001, "ADD_SHIP_FAIL_SHIP_NOT_FOUND"),
    ADD_SHIP_FAIL_FLEET_NOT_FOUND(109002, "ADD_SHIP_FAIL_FLEET_NOT_FOUND"),
    ADD_SHIP_FAIL_ACTIVE_FLEET_NOT_FOUND(109003, "ADD_SHIP_FAIL_ACTIVE_FLEET_NOT_FOUND"),
    ADD_SHIP_FAIL_FLEET_MAX_SHIPS_REACHED(109004, "ADD_SHIP_FAIL_FLEET_MAX_SHIPS_REACHED"),
    ADD_SHIP_FAIL_INSUFFICIENT_COMMANDER_LEVEL(109005, "ADD_SHIP_FAIL_INSUFFICIENT_COMMANDER_LEVEL"),
    ADD_SHIP_FAIL_INSUFFICIENT_MINERAL(109006, "ADD_SHIP_FAIL_INSUFFICIENT_MINERAL"),
    ADD_SHIP_FAIL_INSUFFICIENT_MODULE_POINT(109007, "ADD_SHIP_FAIL_INSUFFICIENT_MODULE_POINT"),

    RESET_SHIP_FAIL_SHIP_NOT_FOUND(109101, "RESET_SHIP_FAIL_SHIP_NOT_FOUND"),
    RESET_SHIP_FAIL_FLEET_ACCESS_DENIED(109102, "RESET_SHIP_FAIL_FLEET_ACCESS_DENIED"),
    RESET_SHIP_FAIL_COMMANDER_NOT_FOUND(109103, "RESET_SHIP_FAIL_COMMANDER_NOT_FOUND"),
    RESET_SHIP_FAIL_FLAGSHIP_FORBIDDEN(109104, "RESET_SHIP_FAIL_FLAGSHIP_FORBIDDEN"),
    RESET_SHIP_FAIL_FLEET_NOT_FOUND(109105, "RESET_SHIP_FAIL_FLEET_NOT_FOUND"),

    MODULE_UNLOCK_FAIL_SHIP_NOT_FOUND(110101, "MODULE_UNLOCK_FAIL_SHIP_NOT_FOUND"),
    MODULE_UNLOCK_FAIL_FLEET_ACCESS_DENIED(110102, "MODULE_UNLOCK_FAIL_FLEET_ACCESS_DENIED"),
    MODULE_UNLOCK_FAIL_COMMANDER_NOT_FOUND(110103, "MODULE_UNLOCK_FAIL_COMMANDER_NOT_FOUND"),
    MODULE_UNLOCK_FAIL_ALREADY_UNLOCKED(110104, "MODULE_UNLOCK_FAIL_ALREADY_UNLOCKED"),
    MODULE_UNLOCK_FAIL_INSUFFICIENT_MINERAL(110105, "MODULE_UNLOCK_FAIL_INSUFFICIENT_MINERAL"),
    MODULE_UNLOCK_FAIL_BODY_MODULE_NOT_FOUND(110106, "MODULE_UNLOCK_FAIL_BODY_MODULE_NOT_FOUND"),
    MODULE_UNLOCK_FAIL_BODY_DATA_NOT_FOUND(110107, "MODULE_UNLOCK_FAIL_BODY_DATA_NOT_FOUND"),
    MODULE_UNLOCK_FAIL_SLOT_INDEX_OUT_OF_BOUNDS(110108, "MODULE_UNLOCK_FAIL_SLOT_INDEX_OUT_OF_BOUNDS"),
    MODULE_UNLOCK_FAIL_INVALID_MODULE_TYPE(110109, "MODULE_UNLOCK_FAIL_INVALID_MODULE_TYPE"),

    MODULE_LEVELUP_FAIL_SHIP_NOT_FOUND(110201, "MODULE_LEVELUP_FAIL_SHIP_NOT_FOUND"),
    MODULE_LEVELUP_FAIL_FLEET_ACCESS_DENIED(110202, "MODULE_LEVELUP_FAIL_FLEET_ACCESS_DENIED"),
    MODULE_LEVELUP_FAIL_MODULE_NOT_FOUND(110203, "MODULE_LEVELUP_FAIL_MODULE_NOT_FOUND"),
    MODULE_LEVELUP_FAIL_LEVEL_MISMATCH(110204, "MODULE_LEVELUP_FAIL_LEVEL_MISMATCH"),
    MODULE_LEVELUP_FAIL_COMMANDER_NOT_FOUND(110205, "MODULE_LEVELUP_FAIL_COMMANDER_NOT_FOUND"),
    MODULE_LEVELUP_FAIL_MODULE_DATA_NOT_FOUND(110206, "MODULE_LEVELUP_FAIL_MODULE_DATA_NOT_FOUND"),
    MODULE_LEVELUP_FAIL_INSUFFICIENT_MINERAL(110207, "MODULE_LEVELUP_FAIL_INSUFFICIENT_MINERAL"),
    MODULE_LEVELUP_FAIL_MINERAL_INVESTED(110208, "MODULE_LEVELUP_FAIL_MINERAL_INVESTED"),

    MODULE_LEVELDOWN_FAIL_SHIP_NOT_FOUND(110301, "MODULE_LEVELDOWN_FAIL_SHIP_NOT_FOUND"),
    MODULE_LEVELDOWN_FAIL_FLEET_ACCESS_DENIED(110302, "MODULE_LEVELDOWN_FAIL_FLEET_ACCESS_DENIED"),
    MODULE_LEVELDOWN_FAIL_MODULE_NOT_FOUND(110303, "MODULE_LEVELDOWN_FAIL_MODULE_NOT_FOUND"),
    MODULE_LEVELDOWN_FAIL_LEVEL_MISMATCH(110304, "MODULE_LEVELDOWN_FAIL_LEVEL_MISMATCH"),
    MODULE_LEVELDOWN_FAIL_COMMANDER_NOT_FOUND(110305, "MODULE_LEVELDOWN_FAIL_COMMANDER_NOT_FOUND"),
    MODULE_LEVELDOWN_FAIL_MODULE_DATA_NOT_FOUND(110306, "MODULE_LEVELDOWN_FAIL_MODULE_DATA_NOT_FOUND"),
    MODULE_LEVELDOWN_FAIL_MINERAL_INVESTED(110307, "MODULE_LEVELDOWN_FAIL_MINERAL_INVESTED"),

    MODULE_GRADEUP_FAIL_SHIP_NOT_FOUND(110401, "MODULE_GRADEUP_FAIL_SHIP_NOT_FOUND"),
    MODULE_GRADEUP_FAIL_FLEET_ACCESS_DENIED(110402, "MODULE_GRADEUP_FAIL_FLEET_ACCESS_DENIED"),
    MODULE_GRADEUP_FAIL_MODULE_NOT_FOUND(110403, "MODULE_GRADEUP_FAIL_MODULE_NOT_FOUND"),
    MODULE_GRADEUP_FAIL_COMMANDER_NOT_FOUND(110404, "MODULE_GRADEUP_FAIL_COMMANDER_NOT_FOUND"),
    MODULE_GRADEUP_FAIL_SAME_MODULE(110405, "MODULE_GRADEUP_FAIL_SAME_MODULE"),
    MODULE_GRADEUP_FAIL_NOT_MATCH_MODULE_TYPE(110406, "MODULE_GRADEUP_FAIL_NOT_MATCH_MODULE_TYPE"),
    MODULE_GRADEUP_FAIL_MINERAL_INVESTED(110407, "MODULE_GRADEUP_FAIL_MINERAL_INVESTED"),
    MODULE_GRADEUP_FAIL_INSUFFICIENT_COMMANDER_LEVEL(110408, "MODULE_GRADEUP_FAIL_INSUFFICIENT_COMMANDER_LEVEL"),
    MODULE_GRADEUP_FAIL_NOT_DIRECT_NEXT_STEP(110409, "MODULE_GRADEUP_FAIL_NOT_DIRECT_NEXT_STEP"),
    MODULE_GRADEUP_FAIL_INSUFFICIENT_MINERAL(110410, "MODULE_GRADEUP_FAIL_INSUFFICIENT_MINERAL"),

    MODULE_GRADEDOWN_FAIL_SHIP_NOT_FOUND(110451, "MODULE_GRADEDOWN_FAIL_SHIP_NOT_FOUND"),
    MODULE_GRADEDOWN_FAIL_FLEET_ACCESS_DENIED(110452, "MODULE_GRADEDOWN_FAIL_FLEET_ACCESS_DENIED"),
    MODULE_GRADEDOWN_FAIL_MODULE_NOT_FOUND(110453, "MODULE_GRADEDOWN_FAIL_MODULE_NOT_FOUND"),
    MODULE_GRADEDOWN_FAIL_COMMANDER_NOT_FOUND(110454, "MODULE_GRADEDOWN_FAIL_COMMANDER_NOT_FOUND"),
    MODULE_GRADEDOWN_FAIL_SAME_MODULE(110455, "MODULE_GRADEDOWN_FAIL_SAME_MODULE"),
    MODULE_GRADEDOWN_FAIL_MINERAL_INVESTED(110456, "MODULE_GRADEDOWN_FAIL_MINERAL_INVESTED"),

    MODULE_UNLOCK_MINERAL_FAIL_SHIP_NOT_FOUND(110501, "MODULE_UNLOCK_MINERAL_FAIL_SHIP_NOT_FOUND"),
    MODULE_UNLOCK_MINERAL_FAIL_FLEET_ACCESS_DENIED(110502, "MODULE_UNLOCK_MINERAL_FAIL_FLEET_ACCESS_DENIED"),
    MODULE_UNLOCK_MINERAL_FAIL_COMMANDER_NOT_FOUND(110503, "MODULE_UNLOCK_MINERAL_FAIL_COMMANDER_NOT_FOUND"),
    MODULE_UNLOCK_MINERAL_FAIL_ALREADY_UNLOCKED(110504, "MODULE_UNLOCK_MINERAL_FAIL_ALREADY_UNLOCKED"),
    MODULE_UNLOCK_MINERAL_FAIL_BODY_MODULE_NOT_FOUND(110505, "MODULE_UNLOCK_MINERAL_FAIL_BODY_MODULE_NOT_FOUND"),
    MODULE_UNLOCK_MINERAL_FAIL_BODY_DATA_NOT_FOUND(110506, "MODULE_UNLOCK_MINERAL_FAIL_BODY_DATA_NOT_FOUND"),
    MODULE_UNLOCK_MINERAL_FAIL_SLOT_INDEX_OUT_OF_BOUNDS(110507, "MODULE_UNLOCK_MINERAL_FAIL_SLOT_INDEX_OUT_OF_BOUNDS"),
    MODULE_UNLOCK_MINERAL_FAIL_INVALID_MODULE_TYPE(110508, "MODULE_UNLOCK_MINERAL_FAIL_INVALID_MODULE_TYPE"),
    MODULE_UNLOCK_MINERAL_FAIL_INSUFFICIENT_MINERAL(110509, "MODULE_UNLOCK_MINERAL_FAIL_INSUFFICIENT_MINERAL"),

    MODULE_LEVELUP_MINERAL_FAIL_SHIP_NOT_FOUND(110601, "MODULE_LEVELUP_MINERAL_FAIL_SHIP_NOT_FOUND"),
    MODULE_LEVELUP_MINERAL_FAIL_FLEET_ACCESS_DENIED(110602, "MODULE_LEVELUP_MINERAL_FAIL_FLEET_ACCESS_DENIED"),
    MODULE_LEVELUP_MINERAL_FAIL_MODULE_NOT_FOUND(110603, "MODULE_LEVELUP_MINERAL_FAIL_MODULE_NOT_FOUND"),
    MODULE_LEVELUP_MINERAL_FAIL_LEVEL_MISMATCH(110604, "MODULE_LEVELUP_MINERAL_FAIL_LEVEL_MISMATCH"),
    MODULE_LEVELUP_MINERAL_FAIL_COMMANDER_NOT_FOUND(110605, "MODULE_LEVELUP_MINERAL_FAIL_COMMANDER_NOT_FOUND"),
    MODULE_LEVELUP_MINERAL_FAIL_MODULE_DATA_NOT_FOUND(110606, "MODULE_LEVELUP_MINERAL_FAIL_MODULE_DATA_NOT_FOUND"),
    MODULE_LEVELUP_MINERAL_FAIL_INSUFFICIENT_MINERAL(110607, "MODULE_LEVELUP_MINERAL_FAIL_INSUFFICIENT_MINERAL"),

    MODULE_LEVELDOWN_MINERAL_FAIL_SHIP_NOT_FOUND(110701, "MODULE_LEVELDOWN_MINERAL_FAIL_SHIP_NOT_FOUND"),
    MODULE_LEVELDOWN_MINERAL_FAIL_FLEET_ACCESS_DENIED(110702, "MODULE_LEVELDOWN_MINERAL_FAIL_FLEET_ACCESS_DENIED"),
    MODULE_LEVELDOWN_MINERAL_FAIL_MODULE_NOT_FOUND(110703, "MODULE_LEVELDOWN_MINERAL_FAIL_MODULE_NOT_FOUND"),
    MODULE_LEVELDOWN_MINERAL_FAIL_LEVEL_MISMATCH(110704, "MODULE_LEVELDOWN_MINERAL_FAIL_LEVEL_MISMATCH"),
    MODULE_LEVELDOWN_MINERAL_FAIL_COMMANDER_NOT_FOUND(110705, "MODULE_LEVELDOWN_MINERAL_FAIL_COMMANDER_NOT_FOUND"),
    MODULE_LEVELDOWN_MINERAL_FAIL_BELOW_POINT_BASELINE(110706, "MODULE_LEVELDOWN_MINERAL_FAIL_BELOW_POINT_BASELINE"),
    MODULE_LEVELDOWN_MINERAL_FAIL_MODULE_DATA_NOT_FOUND(110707, "MODULE_LEVELDOWN_MINERAL_FAIL_MODULE_DATA_NOT_FOUND"),

    MODULE_GRADEUP_MINERAL_FAIL_SHIP_NOT_FOUND(110801, "MODULE_GRADEUP_MINERAL_FAIL_SHIP_NOT_FOUND"),
    MODULE_GRADEUP_MINERAL_FAIL_FLEET_ACCESS_DENIED(110802, "MODULE_GRADEUP_MINERAL_FAIL_FLEET_ACCESS_DENIED"),
    MODULE_GRADEUP_MINERAL_FAIL_MODULE_NOT_FOUND(110803, "MODULE_GRADEUP_MINERAL_FAIL_MODULE_NOT_FOUND"),
    MODULE_GRADEUP_MINERAL_FAIL_COMMANDER_NOT_FOUND(110804, "MODULE_GRADEUP_MINERAL_FAIL_COMMANDER_NOT_FOUND"),
    MODULE_GRADEUP_MINERAL_FAIL_SAME_MODULE(110805, "MODULE_GRADEUP_MINERAL_FAIL_SAME_MODULE"),
    MODULE_GRADEUP_MINERAL_FAIL_NOT_DIRECT_NEXT_STEP(110806, "MODULE_GRADEUP_MINERAL_FAIL_NOT_DIRECT_NEXT_STEP"),
    MODULE_GRADEUP_MINERAL_FAIL_INSUFFICIENT_COMMANDER_LEVEL(110807, "MODULE_GRADEUP_MINERAL_FAIL_INSUFFICIENT_COMMANDER_LEVEL"),
    MODULE_GRADEUP_MINERAL_FAIL_MODULE_DATA_NOT_FOUND(110808, "MODULE_GRADEUP_MINERAL_FAIL_MODULE_DATA_NOT_FOUND"),
    MODULE_GRADEUP_MINERAL_FAIL_INSUFFICIENT_MINERAL(110809, "MODULE_GRADEUP_MINERAL_FAIL_INSUFFICIENT_MINERAL"),

    MODULE_GRADEDOWN_MINERAL_FAIL_SHIP_NOT_FOUND(110851, "MODULE_GRADEDOWN_MINERAL_FAIL_SHIP_NOT_FOUND"),
    MODULE_GRADEDOWN_MINERAL_FAIL_FLEET_ACCESS_DENIED(110852, "MODULE_GRADEDOWN_MINERAL_FAIL_FLEET_ACCESS_DENIED"),
    MODULE_GRADEDOWN_MINERAL_FAIL_MODULE_NOT_FOUND(110853, "MODULE_GRADEDOWN_MINERAL_FAIL_MODULE_NOT_FOUND"),
    MODULE_GRADEDOWN_MINERAL_FAIL_COMMANDER_NOT_FOUND(110854, "MODULE_GRADEDOWN_MINERAL_FAIL_COMMANDER_NOT_FOUND"),
    MODULE_GRADEDOWN_MINERAL_FAIL_SAME_MODULE(110855, "MODULE_GRADEDOWN_MINERAL_FAIL_SAME_MODULE"),
    MODULE_GRADEDOWN_MINERAL_FAIL_BELOW_POINT_BASELINE(110856, "MODULE_GRADEDOWN_MINERAL_FAIL_BELOW_POINT_BASELINE"),

    MODULE_RESET_FAIL_SHIP_NOT_FOUND(110901, "MODULE_RESET_FAIL_SHIP_NOT_FOUND"),
    MODULE_RESET_FAIL_FLEET_ACCESS_DENIED(110902, "MODULE_RESET_FAIL_FLEET_ACCESS_DENIED"),
    MODULE_RESET_FAIL_MODULE_NOT_FOUND(110903, "MODULE_RESET_FAIL_MODULE_NOT_FOUND"),
    MODULE_RESET_FAIL_COMMANDER_NOT_FOUND(110904, "MODULE_RESET_FAIL_COMMANDER_NOT_FOUND"),
    MODULE_RESET_FAIL_BODY_FORBIDDEN(110905, "MODULE_RESET_FAIL_BODY_FORBIDDEN"),
    MODULE_RESET_FAIL_NO_MINERAL_INVESTED(110906, "MODULE_RESET_FAIL_NO_MINERAL_INVESTED"),

    MODULE_RESET_MINERAL_FAIL_SHIP_NOT_FOUND(110951, "MODULE_RESET_MINERAL_FAIL_SHIP_NOT_FOUND"),
    MODULE_RESET_MINERAL_FAIL_FLEET_ACCESS_DENIED(110952, "MODULE_RESET_MINERAL_FAIL_FLEET_ACCESS_DENIED"),
    MODULE_RESET_MINERAL_FAIL_MODULE_NOT_FOUND(110953, "MODULE_RESET_MINERAL_FAIL_MODULE_NOT_FOUND"),
    MODULE_RESET_MINERAL_FAIL_COMMANDER_NOT_FOUND(110954, "MODULE_RESET_MINERAL_FAIL_COMMANDER_NOT_FOUND"),
    MODULE_RESET_MINERAL_FAIL_NO_MINERAL_INVESTED(110955, "MODULE_RESET_MINERAL_FAIL_NO_MINERAL_INVESTED"),

    ZONE_CONTROLLER_FAIL_INVALID_TOKEN(111001, "ZONE_CONTROLLER_FAIL_INVALID_TOKEN"),
    ZONE_CONTROLLER_FAIL_JWT_HAS_COMMANDERID(111002, "ZONE_CONTROLLER_FAIL_JWT_HAS_COMMANDERID"),
    ZONE_CONTROLLER_FAIL_JWT_GET_COMMANDERID(111003, "ZONE_CONTROLLER_FAIL_JWT_GET_COMMANDERID"),
    ZONE_CLEAR_FAIL_COMMANDER_NOT_FOUND(111101, "ZONE_CLEAR_FAIL_COMMANDER_NOT_FOUND"),
    ZONE_CLEAR_FAIL_INSUFFICIENT_SHIPS(111102, "ZONE_CLEAR_FAIL_INSUFFICIENT_SHIPS"),
    ZONE_COLLECT_FAIL_NO_CLEARED_ZONE(111201, "ZONE_COLLECT_FAIL_NO_CLEARED_ZONE"),
    ZONE_COLLECT_FAIL_INVALID_ZONE(111202, "ZONE_COLLECT_FAIL_INVALID_ZONE"),
    ZONE_DESTROY_WAVE_FAIL_COMMANDER_NOT_FOUND(111301, "ZONE_DESTROY_WAVE_FAIL_COMMANDER_NOT_FOUND"),
    ZONE_DESTROY_WAVE_FAIL_ZONE_NOT_FOUND(111302, "ZONE_DESTROY_WAVE_FAIL_ZONE_NOT_FOUND"),
    ZONE_ALREADY_CLEARED(111303, "ZONE_ALREADY_CLEARED"),
    ZONE_NOT_CLEARED(111304, "ZONE_NOT_CLEARED"),
    ZONE_REWARD_ALREADY_CLAIMED(111305, "ZONE_REWARD_ALREADY_CLAIMED"),
    ZONE_PREVIOUS_STAGE_NOT_CLEARED(111306, "ZONE_PREVIOUS_STAGE_NOT_CLEARED"),
    ZONE_CLEAR_FAIL_MINERAL_EXCEED_SERVER(111307, "ZONE_CLEAR_FAIL_MINERAL_EXCEED_SERVER"),
    HEARTBEAT_FAIL_COMMANDER_NOT_FOUND(111401, "HEARTBEAT_FAIL_COMMANDER_NOT_FOUND"),

    PROGRESS_CONTROLLER_FAIL_INVALID_TOKEN(112001, "PROGRESS_CONTROLLER_FAIL_INVALID_TOKEN"),
    PROGRESS_CONTROLLER_FAIL_JWT_HAS_COMMANDERID(112002, "PROGRESS_CONTROLLER_FAIL_JWT_HAS_COMMANDERID"),
    PROGRESS_CONTROLLER_FAIL_JWT_GET_COMMANDERID(112003, "PROGRESS_CONTROLLER_FAIL_JWT_GET_COMMANDERID"),

    PVP_CONTROLLER_FAIL_INVALID_TOKEN(113001, "PVP_CONTROLLER_FAIL_INVALID_TOKEN"),
    PVP_CONTROLLER_FAIL_JWT_HAS_COMMANDERID(113002, "PVP_CONTROLLER_FAIL_JWT_HAS_COMMANDERID"),
    PVP_CONTROLLER_FAIL_JWT_GET_COMMANDERID(113003, "PVP_CONTROLLER_FAIL_JWT_GET_COMMANDERID"),
    PVP_REFRESH_LIMIT_EXCEEDED(113101, "PVP_REFRESH_LIMIT_EXCEEDED"),
    PVP_OPPONENT_FLEET_NOT_FOUND(113201, "PVP_OPPONENT_FLEET_NOT_FOUND"),
    PVP_COMMANDER_LEVEL_TOO_LOW(113202, "PVP_COMMANDER_LEVEL_TOO_LOW"),
    PVP_BATTLE_TOKEN_INVALID(113301, "PVP_BATTLE_TOKEN_INVALID"),








    IAP_CONTROLLER_FAIL_INVALID_TOKEN(115001, "IAP_CONTROLLER_FAIL_INVALID_TOKEN"),
    IAP_CONTROLLER_FAIL_JWT_HAS_COMMANDERID(115002, "IAP_CONTROLLER_FAIL_JWT_HAS_COMMANDERID"),
    IAP_CONTROLLER_FAIL_JWT_GET_COMMANDERID(115003, "IAP_CONTROLLER_FAIL_JWT_GET_COMMANDERID"),
    IAP_PURCHASE_FAIL_INVALID_RECEIPT(115101, "IAP_PURCHASE_FAIL_INVALID_RECEIPT"),
    IAP_PURCHASE_FAIL_GOOGLE_VERIFY(115102, "IAP_PURCHASE_FAIL_GOOGLE_VERIFY"),
    IAP_PURCHASE_FAIL_SUBSCRIPTION_NOT_ACTIVE(115103, "IAP_PURCHASE_FAIL_SUBSCRIPTION_NOT_ACTIVE"),
    IAP_PURCHASE_FAIL_ALREADY_ACTIVE(115104, "IAP_PURCHASE_FAIL_ALREADY_ACTIVE"),
    IAP_DAILY_MINERAL_NOT_VIP(115201, "IAP_DAILY_MINERAL_NOT_VIP"),
    IAP_DAILY_MINERAL_COMMANDER_NOT_FOUND(115202, "IAP_DAILY_MINERAL_COMMANDER_NOT_FOUND"),

    CLIENT_REFRESH_TOKEN_NULL(500001, "CLIENT_REFRESH_TOKEN_NULL"),
    CLIENT_RUNASYNC_FAIL_UNKONW(500002, "CLIENT_RUNASYNC_FAIL_UNKONW"),
    CLIENT_LOGIN_GOOGLE_FAIL_AUTHENTICATION_TIMEOUT(501101, "LOGIN_GOOGLE_FAIL_AUTHENTICATION_TIMEOUT"),
    CLIENT_LOGIN_GOOGLE_FAIL_EXTRACT_AUTHENTICATION(501102, "LOGIN_GOOGLE_FAIL_EXTRACT_AUTHENTICATION"),
    CLIENT_CanAddShip_COMMANDER_NOT_FOUND(510001, "CLIENT_CanAddShip_COMMANDER_NOT_FOUND"),
    CLIENT_CanAddShip_FLEET_MAX_SHIPS_REACHED(510002, "CLIENT_CanAddShip_FLEET_MAX_SHIPS_REACHED"),
    CLIENT_CanAddShip_INSUFFICIENT_COMMANDER_LEVEL(510003, "CLIENT_CanAddShip_INSUFFICIENT_COMMANDER_LEVEL"),
    CLIENT_CanAddShip_INSUFFICIENT_MINERAL(510004, "CLIENT_CanAddShip_INSUFFICIENT_MINERAL"),
    CLIENT_CanAddShip_INSUFFICIENT_MINERAL_RARE(510005, "CLIENT_CanAddShip_INSUFFICIENT_MINERAL_RARE"),
    CLIENT_CanAddShip_INSUFFICIENT_MINERAL_EXOTIC(510006, "CLIENT_CanAddShip_INSUFFICIENT_MINERAL_EXOTIC"),
    CLIENT_CanAddShip_INSUFFICIENT_MINERAL_DARK(510007, "CLIENT_CanAddShip_INSUFFICIENT_MINERAL_DARK"),





    INVALID_DATA_TABLE(5001, "Invalid data table provided"),
    UNKNOWN_ERROR(Integer.MAX_VALUE, "Unknown error");

    private final int code;
    private final String message;

    ServerErrorCode(int code, String message) {
        this.code = code;
        this.message = message;
    }

    public int getCode() {
        return code;
    }

    public String getMessage() {
        return message;
    }
}

